# Generated by Django 4.1.1 on 2022-09-27 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Category image')),
                ('title', models.CharField(max_length=255, verbose_name='Category title')),
                ('description', models.TextField(verbose_name='Category description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category_post',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Post image')),
                ('title', models.CharField(max_length=255, verbose_name='Post title')),
                ('description', models.TextField(verbose_name='Post description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Post date created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.categorypost', verbose_name='Post category')),
                ('like_post', models.ManyToManyField(blank=True, null=True, related_name='like_post', to=settings.AUTH_USER_MODEL, verbose_name='Do you like this post?')),
                ('view_post', models.ManyToManyField(blank=True, null=True, related_name='view_post', to=settings.AUTH_USER_MODEL, verbose_name='You viewed this post')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='MySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Subscribe time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='My subscription user')),
            ],
            options={
                'verbose_name': 'My subscription',
                'verbose_name_plural': 'My subscriptions',
                'db_table': 'my_subscription',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title of comments')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Text of comments')),
                ('status', models.BooleanField(default=True, verbose_name='Comment visibility')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of comments')),
                ('post_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='post.post', verbose_name='Name of Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Block time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Blocked user')),
            ],
            options={
                'verbose_name': 'Blocked user',
                'verbose_name_plural': 'Blocked users',
                'db_table': 'blocked_user',
            },
        ),
    ]
